### ISSUE TITLE
Allow setting custom detectors in Scanners

### ISSUE THREAD

**Issue by joarobles** [thescalaguy/detectpii#3]
As far as I understand, in order to extend the detection one has to create at least 2 classes:

- An instance of `Scanner`
- An optional instance of `Detector`

It would be nice to be able to instantiate a `MetadataScanner` with a optional custom `Detector` (using by default the `ColumnNameRegexDetector`), like this:

```python
pipeline = PiiDetectionPipeline(
    catalog=catalog,
    scanners=[
        MetadataScanner(detector=SpanishColumnNameRegexDetector()),
    ]
)
```

**Comment by thescalaguy** [comment]
Hey @joarobles,

[Here’s a PR](https://github.com/thescalaguy/detectpii/pull/4) which enables passing detectors as arguments to scanners. This should allow adding detectors for different languages that reuse the machinery of the scanners. In essence, a scanner simply passes data fetched from a catalog into a detector.

**Comment by joarobles** [comment]
Excellent, thanks @thescalaguy!
