### ISSUE TITLE
SQLAlchemy agnostic Catalog

### ISSUE THREAD

**Issue by joarobles** [thescalaguy/detectpii#7]
The `Catalog` class has a direct dependency on the SQLAlchemy `Engine`:

```
class Catalog:

    @abc.abstractmethod
    def engine(self) -> Engine:
        raise NotImplementedError()
```

I guess this method could be extracted out of the abstraction, for the implementing classes to decide the way to extract table and column names (i.e.: GCP BigQuery could use the HTTP API).

Otherwise `sqlalchemy` must be a required dependency, what do you think?

**Comment by thescalaguy** [comment]
Hey @joarobles,

I believe that’s a nice idea. Take a look at the PR linked above this comment. 

What do you think? 

:)

**Comment by thescalaguy** [comment]
Hey @joarobles,

As a part of the refactoring that we discussed, I’ve raised a PR to add support for Google BigQuery.

:)

**Comment by joarobles** [comment]
Excellent, thanks @thescalaguy and sorry for the delay.

I've seen both PR and everything looks good!

**Comment by thescalaguy** [comment]
@joarobles I’ve merged both the PRs and will release the new version to pypi shortly.
